### ISSUE TITLE
revert_to! without save

### ISSUE THREAD

**Issue by geetarista** [laserlemon/vestal_versions#3]
I'm questioning the usefulness of creating an extra version every time I use revert_to!. I feel that this method should change to a specific version and keep it there, as opposed to changing to the version and then saving the record, which creates a new and duplicated/unnecessary version.

I know that you create a new version every time a record is saved, but I'm wondering if this should be handled differently or overridden when using revert_to!. I just foresee a huge mess of duplicate versions when I should just be able to switch between them.

**Comment by laserlemon** [comment]
Robby,

The purpose of creating a new version is to be able to continue the chain _after_ a `revert_to!` call. If a model is at version 4 and i `revert_to!` version 2, and if the version number were kept at 2, what do you propose should happen the next time the model is saved? I see a few possibilities:
- The version 3 changes could be clobbered
- The version number could jump from 2 to 5
- Some sort of branching is mechanism could allow parallel third versions (think Back to the Future)

Instead I chose to allow reverting to version 2 to create a new version (5) because:
- I don't want to throw out any historical information
- When a model holds a certain version is simply determined by the version's `created_at` column. Reverting to (and keeping) an earlier version doesn't accurately represent the changes that lead to that point or when (and for how long) that version was held
- While branching is a possibility for the future, I'm reluctant to add too much complexity since the killer feature was always meant to be simplicity

For working with a model at an earlier version without creating a new version, try using the non-bang `revert_to` method instead. Hope this helps,

Steve
