### ISSUE TITLE
changed_by

### ISSUE THREAD

**Issue by petrblaho** [laserlemon/vestal_versions#7]
Hi.
I am using your vestal_versions.
But I miss something like changed_by , where will be saved id of user who commited change to versioned data. I want to track down all chages on differents models by user.
Are you planning similiar feature?
I think more of vestal_versions' users would welcome similiar feature.
With regards Petr Blaho

**Comment by cjk** [comment]
+1
It's definitely useful being able to associate users to versions. Hope this gets implemented.

**Comment by laserlemon** [comment]
Petr,

Thanks for the suggestion. I hadn't planned on adding such a feature initially as I wanted to confine the plugin's functionality to the model layer and it seems like this would need to creep up to the controller. But as always, I'm willing to consider this if there's a clear need for it.

I'll work on a clean way to implement the feature and of course, feel free to fork and have a stab at it yourself! Thanks again,

Steve

**Comment by laserlemon** [comment]
Version 1.0 of vestal_versions is currently being developed and this is on the to-do list. The ability to record the responsible party and notes along with versions will be added.

**Comment by KevinTriplett** [comment]
My suggestion (and what we're doing on my app) is to give the User model a current_user method that returns a user id. That easily implements the changed_by feature. You can provide examples of how to easily implement that method, the current best practices seem to be 1) in the authentication module, 2) in the controller and 3) a thread variable. There are several blog posts on the net about passing the current_user id to the User model. Of course, it would be nice for vestal_versions to use User.current_user by default but allow the class and method names to be customized.

**Comment by laserlemon** [comment]
The front-runner idea for this implementation is to add an optional accessor on the model called either `changed_by` or `updated_by` (any favorites?). This would be used to set the user in the versions table in one of two ways:
1. The user passed via `updated_by` is an `ActiveRecord::Base` object which will set the `user_id` and `user_type` columns. Versions will have a new polymorphic `belongs_to :user` association.
2. The user passed is something else; in which case, we take the `to_s` of that value and throw it into a `user_name` column.

Then the `user` method on the version model will be configured to grab either the AR object or the string depending on which was set.

**Comment by laserlemon** [comment]
And... built. Check out the 1.0 branch for details.

**Comment by KevinTriplett** [comment]
[UPDATE: wow that was fast -- here's my comment before it was built:) ]

That's very flexible -- the developer would define this method on each versionable model, if I understand correctly. If you wanted to make it even more flexible, you would check the method's return type and store either the string or the id/type pair. I like chaged_by since update has a special meaning the Rails universe (of course, I understand you are eliminating the creation version, so maybe updated_by is appropriate :)

**Comment by laserlemon** [comment]
Kevin,

There's no need to define any further methods on the model. The user tracking feature just added to 1.0 adds the `updated_by` accessor for you and passes it along to the created version. And as you said, it sets the polymorphic `user` if the given value is an ActiveRecord object, or the `user_name` otherwise. That's all done automatically.

**Comment by KevinTriplett** [comment]
Ah, I see -- no methods are involved, we just pass the :updated_by value (whether AR object or string) in the #update_attributes method. That's a good solution, IMO, flexible and controller-side. I don't think anyone can complain and it's less magical.

**Comment by dfurber** [comment]
@question.update_attributes params[:question].merge(:updated_by => current_user)
gives me "unknown attribute :updated_by"

on Question model:
versioned :if => :really_create_a_version?

Is there something else I need to do?

**Comment by dfurber** [comment]
Yes - dummy - update the gem! :)
